project:
  type: website

website:
  title: "Filipe P. de Farias"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  about:
    template: trestles
  
  page-footer: 
    left: "August, 2022"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true



