name: Build and Deploy
on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # === Build Franklin site ===
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - run: julia -e '
              using Pkg; Pkg.activate("."); Pkg.instantiate();
              using NodeJS; run(`$(npm_cmd()) install highlight.js`);
              using Franklin;
              optimize()'

      # === Copy UFC_MSc_Thesis folder into final site ===
      - name: Copy UFC_MSc_Thesis into site
        run: |
          mkdir -p __site/UFC_MSc_Thesis
          cp -r UFC_MSc_Thesis/* __site/UFC_MSc_Thesis/

      # === Deploy to GitHub Pages ===
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: __site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
